### ISSUE TITLE
Error when running enumall script

### ISSUE THREAD

**Issue by nsonaniya2010** [jhaddix/domain#24]
After searching domains from Bing following error happen:
```
SUMMARY
-------
[*] 1 total (1 new) hosts found.
[!] Invalid module name.
Traceback (most recent call last):
  File "./enumall.py", line 98, in <module>
    run_recon(domainList, bruteforceList)
  File "./enumall.py", line 52, in run_recon
    run_module(reconb, module, domain)
  File "./enumall.py", line 37, in run_module
    x.do_set("SOURCE " + domain)
AttributeError: 'NoneType' object has no attribute 'do_set'
```

**Comment by M1tulPatel** [comment]
I'm facing the same issue.

```
Traceback (most recent call last):
  File "/home/kali/Downloads/domained/bin/domain/enumall.py", line 98, in <module>
    run_recon(domainList, bruteforceList)
  File "/home/kali/Downloads/domained/bin/domain/enumall.py", line 46, in run_recon
    reconb.init_workspace(wspace)
AttributeError: 'Recon' object has no attribute 'init_workspace'
```
