### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by murtough226** [jhaddix/domain#32]
Traceback (most recent call last):
File "./enumall.py", line 28, in <module>
from recon.core import base
File "/usr/share/recon-ng/recon/core/base.py", line 32
framework.Framework._spool.write(f"{args[0]}{os.linesep}")
                                                                                           ^
SyntaxError: invalid syntax

**Comment by murtough226** [comment]
The syntax error is for the closing quotes.. no idea why its referencing something else..

**Comment by smallpygmy** [comment]
Are you using recon-ng v5? If so, downgrade to v4 and it should work.

**Comment by Oneiroi** [comment]
recon-ng v5 is python3, this tool is python2, there is effort in #34 to port to python3 + recon-ng v5 however this is not as yet complete.

**Comment by EzioRaison** [comment]
This way worked or me :

1. What i did is cloned this https://github.com/methos2016/recon-ng. It's just 5mb.
2. Changed the path in config.py and enumall.py in accordance to newly downloaded recon-ng.
3.That's it.

The main problem is that new recong-ng is based on pytohn3 and this script dependencies are of older recon-ng that was based on python2.
