### ISSUE TITLE
./recon-ng error

### ISSUE THREAD

**Issue by modrler** [jhaddix/domain#40]
Hey, I encountered this error at the last stage of running recon-ng in git bash. If someone understands, please help me solve it

`$ ./recon-ng`
```
Traceback (most recent call last):
  File "C:\Users\User\recon-ng\recon-ng", line 8, in <module>
    from recon.core import base
  File "C:\Users\User\recon-ng\recon\core\base.py", line 7, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```
![image](https://github.com/jhaddix/domain/assets/129308493/27631972-f9a9-4adf-bd17-99143b492080)

[Recon-ng on Github](https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#migrating-keys)

**Comment by ams-10** [comment]
can someone please tell me where to find the working tool
